/**
 * Auto-update host (F-slice #2) — bridges the frontend's Tauri updater
 * contract onto electron-updater, per the competitor-survey selection
 * (memory `reference-electron-autoupdate-across-competitors`):
 * `electron-updater` + generic provider pointed at the EXISTING Aliyun OSS
 * bucket that already serves the Tauri `latest.json` — the feed just gains a
 * `latest-mac.yml` (generated by electron-builder at dist time, never
 * hand-written: the sha512 must be computed from the final artifact).
 *
 * ## Frontend contract (verbatim from @tauri-apps/plugin-updater dist-js)
 * src/core/updates/checker.ts calls exactly two plugin paths:
 *  - `check()` → invoke('plugin:updater|check', {...}) → metadata
 *    `{ rid, currentVersion, version, date, body, rawJson }` or null.
 *  - `Update.downloadAndInstall(onEvent)` →
 *    invoke('plugin:updater|download_and_install', { onEvent: Channel, rid })
 *    with Started/Progress/Finished events:
 *      { event: 'Started',  data: { contentLength?: number } }
 *      { event: 'Progress', data: { chunkLength: number } }
 *      { event: 'Finished' }
 * Channel delivery rides the same `tauri:callback` bridge as fs watch
 * (fsWatchHost.cjs header documents the `{ index, message }` payload shape).
 * `Update.close()` → plugin:resources|close, which fsWatchHost owns; an
 * updater rid is unknown to its table so the close is a harmless no-op.
 * The two-step `download`/`install` commands are NOT used by the frontend
 * and have no electron-updater equivalent (install happens at quit) — they
 * reject with a clear error rather than pretending.
 *
 * ## Install-at-restart semantics
 * Tauri's downloadAndInstall installs in place and the app keeps running
 * until the user clicks "restart" (plugin:process|restart). electron-updater
 * separates download (here) from install (quitAndInstall). To preserve the
 * frontend flow, desktopHost's processRestart calls
 * `quitAndInstallIfPending()` — when a downloaded update is pending, restart
 * becomes `autoUpdater.quitAndInstall()` instead of plain relaunch (with the
 * quitting guard marked first so the preventable-close handler lets the
 * native window-close through — see that function's JSDoc).
 * `autoInstallOnAppQuit` stays on as a safety net (normal quit also applies
 * the update).
 *
 * ## Feed resolution
 *  - Official packaged build: release CI embeds `app-update.yml` plus the
 *    immutable `officialBuild` marker → generic provider at the OSS bucket.
 *    Source/fork packages have neither and keep the updater disabled.
 *  - Dev/harness: armed only when ABU_UPDATER_FEED_URL is set (e.g. the mock
 *    feed in electron/spike/updaterVerify.cjs) — forceDevUpdateConfig plus an
 *    explicit generic feed. Without it, check() reports null (updater idle in
 *    dev, matching the pre-slice behavior).
 */
'use strict';

const { app } = require('electron');
const { parseChannelId, sendChannelMessage } = require('./channelBridge.cjs');
const { isOfficialBuild } = require('./releaseMetadata.cjs');

/** Sentinel returned when `cmd` isn't one of the updater family. */
const UPDATER_MISS = Symbol('updater-dispatch-miss');
// Production feed URLs live only in the official build workflow and are
// embedded into app-update.yml. Keeping them out of the base builder config
// prevents a fork package from inheriting the official channel.

/** @type {import('electron-updater').AppUpdater | null} */
let updater = null;
let configured = false;
/** rid handed to the renderer's Update resource; single pending check result. */
let nextRid = 90001;
/** Set once download_and_install completed; consumed by processRestart. */
let pendingInstall = false;

function log(msg) {
  console.log(`[updaterHost] ${msg}`);
}

/**
 * Lazy singleton: `require('electron-updater')` is deferred so plain-Node
 * harnesses that never touch updater commands don't pay for (or crash on)
 * the electron-updater import.
 */
function getUpdater() {
  if (configured) return updater;
  configured = true;

  // A source/fork package must never consume Abu's production feed merely
  // because it retained the upstream app id or product name. Official CI sets
  // the immutable package marker and embeds app-update.yml together.
  if (app.isPackaged && !isOfficialBuild(app)) {
    log('non-official packaged build — updater disabled');
    updater = null;
    return updater;
  }

  // The env override is DEV/HARNESS ONLY. A packaged (production) build must
  // never honor it: an attacker-controlled environment (wrapper script, shell
  // profile) could otherwise silently repoint the update feed — packaged
  // builds read exclusively the embedded app-update.yml.
  const feedOverride = app.isPackaged ? undefined : process.env.ABU_UPDATER_FEED_URL;
  if (app.isPackaged && process.env.ABU_UPDATER_FEED_URL) {
    console.warn('[updaterHost] ABU_UPDATER_FEED_URL is ignored in packaged builds (embedded app-update.yml only)');
  }
  if (!app.isPackaged && !feedOverride) {
    // Dev without an explicit feed: stay idle. electron-updater would refuse
    // anyway ("application is not packed"), just noisier.
    log('dev shell without ABU_UPDATER_FEED_URL — updater idle, check() reports no update');
    updater = null;
    return updater;
  }

  const { autoUpdater } = require('electron-updater');
  const fs = require('node:fs');
  const path = require('node:path');

  // Store update payloads in the user's app-data directory instead of the
  // system temp folder to avoid consuming C:\/tmp space on Windows.
  const appDataDir = app.getPath('appData');
  const cacheDir = path.join(appDataDir, 'abu', 'abu-updater-cache');
  try {
    fs.mkdirSync(cacheDir, { recursive: true });
    autoUpdater.downloadToDir = cacheDir;
    log(`update cache directory set to: ${cacheDir}`);
  } catch (err) {
    console.warn('[updaterHost] failed to create update cache dir:', err);
  }

  autoUpdater.autoDownload = false; // the frontend drives download explicitly
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.logger = {
    info: (m) => log(`electron-updater: ${m}`),
    warn: (m) => console.warn(`[updaterHost] electron-updater: ${m}`),
    error: (m) => console.error(`[updaterHost] electron-updater: ${m}`),
    debug: () => {},
  };
  if (feedOverride) {
    // NOT setFeedURL: that only swaps the check-time provider —
    // downloadUpdate still resolves `configOnDisk` (for updaterCacheDirName,
    // AppUpdater.js ~545), which in dev reads `<appPath>/dev-app-update.yml`
    // and ENOENTs. Writing a real config file and pointing updateConfigPath
    // at it feeds BOTH paths from one source.
    const configDir = path.join(app.getPath('appData'), 'abu', 'abu-updater-cache');
    fs.mkdirSync(configDir, { recursive: true });
    const configPath = path.join(configDir, `abu-updater-dev-config-${process.pid}.yml`);
    fs.writeFileSync(
      configPath,
      `provider: generic\nurl: ${feedOverride}\nupdaterCacheDirName: abu-updater-dev-cache\n`,
      'utf8'
    );
    // pid-suffixed (concurrent dev shell + harness must not race one file);
    // remove it on quit so repeated runs don't accumulate in the OS tmp dir.
    app.on('will-quit', () => {
      try {
        fs.rmSync(configPath, { force: true });
      } catch {
        /* best-effort */
      }
    });
    autoUpdater.forceDevUpdateConfig = true;
    autoUpdater.updateConfigPath = configPath;
    log(`feed override via ABU_UPDATER_FEED_URL: ${feedOverride} (config at ${configPath})`);
  }
  // Packaged with no override: the embedded app-update.yml (electron-builder
  // `publish` block → generic provider at OSS_FEED_URL) is picked up
  // automatically; nothing to do here.

  updater = autoUpdater;
  return updater;
}

/** Map electron-updater releaseNotes (string | ReleaseNoteInfo[] | null) to the single string Tauri's `body` carries. */
function notesToBody(releaseNotes) {
  if (typeof releaseNotes === 'string') return releaseNotes;
  if (Array.isArray(releaseNotes)) {
    return releaseNotes.map((n) => (typeof n === 'string' ? n : n && n.note ? n.note : '')).join('\n');
  }
  return '';
}

/** plugin:updater|check → Update metadata or null. */
async function check() {
  const au = getUpdater();
  if (!au) return null;
  const result = await au.checkForUpdates();
  if (!result || !result.isUpdateAvailable) return null;
  const info = result.updateInfo;
  return {
    rid: nextRid++,
    currentVersion: app.getVersion(),
    version: info.version,
    date: info.releaseDate || '',
    body: notesToBody(info.releaseNotes),
    rawJson: JSON.parse(JSON.stringify(info)),
  };
}

/**
 * plugin:updater|download_and_install → download via electron-updater with
 * Tauri-shaped progress events; the actual install applies at restart/quit
 * (see header). Rejects on download/verification failure (e.g. sha512
 * mismatch) so the frontend's catch path resets its progress UI.
 * @param {Record<string, unknown>} a
 * @param {Electron.IpcMainInvokeEvent | undefined} event
 */
async function downloadAndInstall(a, event) {
  const au = getUpdater();
  if (!au) throw new Error('updater not armed (dev shell without ABU_UPDATER_FEED_URL)');

  const callbackId = parseChannelId(a.onEvent);
  const sender = event && event.sender;
  let index = 0;
  const send = (message) => {
    if (callbackId === null) return;
    if (sendChannelMessage(sender, callbackId, index, message)) index++;
  };

  // A new download invalidates any previously downloaded update: if THIS
  // download fails, a stale flag from an earlier success must not route
  // restart through quitAndInstall against torn-down/replaced squirrel state.
  pendingInstall = false;

  let started = false;
  const onProgress = (p) => {
    if (!started) {
      started = true;
      send({ event: 'Started', data: { contentLength: p.total } });
    }
    // Keep the public callback Tauri-compatible while also carrying Electron's
    // absolute counters. The renderer prefers these optional fields so a
    // throttled/coalesced delta stream cannot under-report real progress.
    send({
      event: 'Progress',
      data: {
        chunkLength: p.delta,
        total: p.total,
        transferred: p.transferred,
      },
    });
  };
  au.on('download-progress', onProgress);
  try {
    await au.downloadUpdate();
    pendingInstall = true;
    send({ event: 'Finished' });
  } finally {
    au.removeListener('download-progress', onProgress);
  }
  return null;
}

/**
 * Called by desktopHost's processRestart. When a downloaded update is
 * pending, takes over the restart: marks tauriHost's quitting guard (the
 * native Squirrel quitAndInstall closes windows BEFORE any before-quit
 * fires, so without the mark the preventable-close handler would
 * preventDefault the close, emit 'close-requested' to the renderer, and the
 * install would silently never happen) and calls quitAndInstall. Returns
 * true when it took over (caller must NOT also relaunch), false when there
 * is nothing pending or quitAndInstall threw (caller falls back to a plain
 * relaunch into the current version).
 *
 * pendingInstall is deliberately NOT cleared on the happy path:
 * MacUpdater.quitAndInstall can return without quitting (native Squirrel
 * still fetching from the local proxy — it registers an update-downloaded
 * listener and installs when ready). If that fetch has failed instead, the
 * app keeps running; keeping the flag makes the Restart button retryable
 * rather than silently booting the old version on the second click.
 */
function quitAndInstallIfPending() {
  if (!pendingInstall || !updater) return false;
  // Lazy require: tauriHost requires this module at top level, so requiring
  // it back at load time WOULD be a genuine cycle; at call time it's settled.
  const { markQuitting } = require('./tauriHost.cjs');
  try {
    markQuitting();
    updater.quitAndInstall();
    return true;
  } catch (err) {
    pendingInstall = false;
    console.warn(
      `[updaterHost] quitAndInstall failed — falling back to plain relaunch: ${err instanceof Error ? err.message : String(err)}`
    );
    return false;
  }
}

/**
 * Map a `plugin:updater|*` command. Returns UPDATER_MISS for anything else so
 * tauriHost falls through to its default dispatch.
 * @param {string} cmd
 * @param {{ args?: Record<string, unknown>, event?: Electron.IpcMainInvokeEvent }} payload
 */
function updaterDispatch(cmd, { args, event } = {}) {
  const a = args || {};
  switch (cmd) {
    case 'plugin:updater|check':
      return check();
    case 'plugin:updater|download_and_install':
      return downloadAndInstall(a, event);
    case 'plugin:updater|download':
    case 'plugin:updater|install':
      // No electron-updater equivalent of Tauri's two-step download/install
      // (install happens at quit). The frontend only ever calls
      // download_and_install; fail loudly rather than half-pretending.
      return Promise.reject(
        new Error(`${cmd}: not supported in the Electron shell — use downloadAndInstall`)
      );
    default:
      return UPDATER_MISS;
  }
}

/** Observability (harness assertions): whether a downloaded update awaits install. */
function hasPendingInstall() {
  return pendingInstall;
}

module.exports = { updaterDispatch, quitAndInstallIfPending, hasPendingInstall, UPDATER_MISS };
